title: Dr. Zach Palmer's Website
description: A colletion of my academic works and blogs.
url: "https://zpalmer618.github.io" # the subpath of
nav_items:
  - title: Home
    url: /
  - title: About
    url: /about.html
  - title: Blogs
    url: /blog.html